# -*- coding: utf-8 -*-
"""python_basics_<mohan>.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RnKW6KlmSI-OLkUZX5xi94O_hyebStCE
"""



"""Task 1: Variables and Data Types Create variables to store a person's name (string), age (integer), height in meters (float), and whether they are a student (boolean). Print all four values in a single print() statement.

Task 2: String Formatting Using the variables from Task 1, print a sentence in the following format: Name: <name> | Age: <age> | Height: <height> | Student: <is_student>

Task 3: Arithmetic Operations Using the age variable, calculate and print:

Age in months
Age in days (assume 365 days/year)
The remainder when age is divided by 7
Age raised to the power of 2
"""
#task1 
name="mohan"
age=21
height=5.7
student=True
print(name,age,height,student)

#task2
print(f"name:{name}|age:{age}|height:{height}|student:{student}|")

#task3
age_in_month=21*12
age_in_days=21/365
remainder_age=21%7
age_raised=2**21
print("age in month:",{age_in_month})
print("age in days:",{age_in_days})
print("remainder age:",{remainder_age})
print("age raised:",{age_raised})